# Generated by Django 4.1.4 on 2023-01-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='owner',
        ),
    ]
