# Generated by Django 4.1.4 on 2023-01-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_remove_message_recipients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'message', 'verbose_name_plural': 'Messages'},
        ),
    ]
